# =============================================================================
# ini_generator.R — Generate pyGenomeTracks tracks.ini files
# =============================================================================

#' Format a single value for INI output
#'
#' @param x value to format
#' @return character string
#' @export
format_ini_value <- function(x) {
  if (is.null(x) || (length(x) == 1 && is.na(x))) return(NULL)
  if (is.logical(x)) return(if (x) "true" else "false")
  if (is.numeric(x)) return(as.character(x))
  as.character(x)
}

#' Convert a track object to an INI block string
#'
#' @param track list representing a single track
#' @param schema schema list from load_track_schema
#' @return character string for one [section] block
#' @export
track_to_ini_block <- function(track, schema) {
  track_type <- track$track_type
  schema_entry <- schema$tracks[[track_type]]
  if (is.null(schema_entry)) stop(sprintf("Unknown track type: %s", track_type))

  # Section header: use track_name if set, else a safe default
  raw_name  <- track$track_name %||% schema_entry$label %||% track_type
  # Sanitize: no brackets allowed in INI section name
  safe_name <- gsub("[\\[\\]]", "", raw_name)
  if (nchar(trimws(safe_name)) == 0) safe_name <- track_type

  lines <- c(sprintf("[%s]", safe_name))

  # file line first (required for most types)
  file_path <- track$file_path %||% ""
  if (isTRUE(schema_entry$file_required) && nchar(file_path) > 0) {
    lines <- c(lines, sprintf("file = %s", file_path))
  }

  # file_type
  pgt_type <- schema_entry$pygenometracks_file_type
  if (!is.null(pgt_type) && nchar(pgt_type) > 0) {
    lines <- c(lines, sprintf("file_type = %s", pgt_type))
  }

  # Parameters: merge schema defaults with track-specific params
  param_defs  <- schema_entry$params %||% list()
  track_params <- track$params %||% list()

  for (param_name in names(param_defs)) {
    # Skip params that map to special keys handled above
    if (param_name == "file_type") next

    # Use track-specific value if set, else schema default
    value <- track_params[[param_name]]
    if (is.null(value)) value <- param_defs[[param_name]]$default
    if (is.null(value)) next

    ini_val <- format_ini_value(value)
    if (is.null(ini_val) || nchar(trimws(ini_val)) == 0) next

    # Skip "auto" for min/max since that is the pyGenomeTracks default (can omit)
    if (param_name %in% c("min_value", "max_value") && ini_val == "auto") next

    lines <- c(lines, sprintf("%s = %s", param_name, ini_val))
  }

  # Append a blank line after each block
  lines <- c(lines, "")
  paste(lines, collapse = "\n")
}

#' Generate a full tracks.ini content string from a list of tracks
#'
#' @param tracks list of track objects (enabled only, ordered)
#' @param schema schema list from load_track_schema
#' @return character string with full INI content
#' @export
generate_tracks_ini <- function(tracks, schema) {
  if (length(tracks) == 0) stop("No tracks provided for INI generation")

  # Sort by order field if present
  orders <- vapply(tracks, function(t) as.integer(t$order %||% 999L), integer(1))
  tracks <- tracks[order(orders)]

  # Filter to enabled tracks only
  tracks <- Filter(function(t) isTRUE(t$enabled), tracks)
  if (length(tracks) == 0) stop("No enabled tracks available for INI generation")

  blocks <- vapply(tracks, function(t) {
    tryCatch(track_to_ini_block(t, schema), error = function(e) {
      warning(sprintf("Skipping track '%s': %s", t$track_name %||% "?", e$message))
      ""
    })
  }, character(1))

  header <- paste0(
    "# tracks.ini — generated by rGenomeTrackUI\n",
    "# Generated: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n",
    "# DO NOT EDIT while a run is in progress\n\n"
  )

  paste0(header, paste(blocks, collapse = "\n"))
}

#' Write a tracks.ini file to disk
#'
#' @param tracks list of track objects
#' @param schema schema list
#' @param path destination file path
#' @return invisible path
#' @export
write_tracks_ini <- function(tracks, schema, path) {
  ini_text <- generate_tracks_ini(tracks, schema)
  ensure_dir(dirname(path))
  writeLines(ini_text, path)
  invisible(path)
}
