# =============================================================================
# shell_script_generator.R — Generate pyGenomeTracks shell scripts
# =============================================================================

#' Generate shell script content for a pyGenomeTracks run
#'
#' @param run_path path to run directory
#' @param regions character vector of "chr:start-end" strings
#' @param figure_settings named list of figure settings
#' @param conda_env Conda environment name (default "rgenometrackui")
#' @return character string with script content
#' @export
generate_pygenometracks_shell_script <- function(run_path, regions, figure_settings,
                                                  conda_env = "rgenometrackui") {
  fs              <- figure_settings %||% list()
  output_format   <- fs$output_format  %||% "png"
  width           <- fs$width          %||% 38
  dpi             <- fs$dpi            %||% 150
  output_basename <- fs$output_basename %||% "figure"
  title           <- fs$title          %||% ""

  if (length(regions) == 0) regions <- c("chr1:1-1000000")

  # Resolve the absolute pyGenomeTracks binary at generation time for robust
  # subprocess execution (conda may not be in PATH of the calling process).
  # Fallback to 'conda run -n <env> pyGenomeTracks' for standalone/terminal use.
  pygt_bin <- Sys.which("pyGenomeTracks")
  if (nchar(pygt_bin) > 0) {
    pygt_call <- shQuote(pygt_bin)
    conda_note <- sprintf("# pyGenomeTracks binary: %s", pygt_bin)
  } else {
    pygt_call <- sprintf("conda run -n %s pyGenomeTracks", conda_env)
    conda_note <- sprintf("# conda env: %s (pyGenomeTracks not found in PATH at generation time)", conda_env)
  }

  # Build per-region commands
  region_cmd_lines <- vapply(regions, function(reg) {
    safe <- sanitize_region_for_filename(reg)
    out  <- sprintf('outputs/multi_region/%s_%s.%s', output_basename, safe, output_format)

    cmd_parts <- c(
      sprintf('%s \\', pygt_call),
      sprintf('    --tracks config/tracks.ini \\'),
      sprintf('    --region "%s" \\', reg),
      sprintf('    --outFileName "%s" \\', out),
      sprintf('    --width %s \\', width),
      sprintf('    --dpi %s', dpi)
    )
    if (nchar(title) > 0) {
      cmd_parts[length(cmd_parts)] <- paste0(cmd_parts[length(cmd_parts)], " \\")
      cmd_parts <- c(cmd_parts, sprintf('    --title "%s"', gsub('"', '\\"', title)))
    }

    paste(c(
      sprintf('echo "[pyGenomeTracks] Running region: %s"', reg),
      paste(cmd_parts, collapse = "\n"),
      sprintf('if [ $? -eq 0 ]; then echo "[OK] %s"; else echo "[ERROR] Region %s failed" >&2; fi',
              out, reg),
      ""
    ), collapse = "\n")
  }, character(1))

  lines <- c(
    "#!/usr/bin/env bash",
    "# =============================================================================",
    "# run_pyGenomeTracks.sh — Generated by rGenomeTrackUI",
    sprintf("# Generated: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
    sprintf("# Conda env: %s", conda_env),
    conda_note,
    "# Run from the run directory:",
    "#   bash scripts/run_pyGenomeTracks.sh",
    "# =============================================================================",
    "",
    "set -euo pipefail",
    "",
    "# Change to the run directory (script is in scripts/)
SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
    "RUN_DIR=\"$(dirname \"$SCRIPT_DIR\")\"",
    "cd \"$RUN_DIR\"",
    "",
    "# Set headless matplotlib backend",
    "export MPLBACKEND=Agg",
    "",
    "# Create output directory",
    "mkdir -p outputs/multi_region",
    "",
    "# Redirect logs",
    "STDOUT_LOG=\"logs/stdout.log\"",
    "STDERR_LOG=\"logs/stderr.log\"",
    "",
    "echo \"[INFO] Run started: $(date)\" | tee -a \"$STDOUT_LOG\"",
    "echo \"[INFO] Working directory: $RUN_DIR\"",
    "",
    region_cmd_lines,
    "",
    "echo \"[INFO] Run completed: $(date)\" | tee -a \"$STDOUT_LOG\""
  )

  script_text <- paste(lines, collapse = "\n")
  write_pygenometracks_shell_script(run_path, script_text)
  invisible(script_text)
}

#' Write the shell script to disk (with execute permission)
#'
#' @param run_path path to run directory
#' @param script_text character string with script content
#' @return invisible path
#' @export
write_pygenometracks_shell_script <- function(run_path, script_text) {
  path <- file.path(run_path, "scripts", "run_pyGenomeTracks.sh")
  ensure_dir(dirname(path))
  writeLines(script_text, path)
  # Make executable
  Sys.chmod(path, mode = "0755")
  invisible(path)
}
